# Numpy Library Mastery

### Install Numpy Library 

In [1]:
#!python -m pip install numpy

### 1. Import the NumPy library and give it the alias np.

In [2]:
import numpy as np

### 2. Create a 1D NumPy array named `my_list` containing the integers `[1, 2, 3, 4, 5]` and a 2D NumPy array (3x3) named `my_matrix` from the list of lists: `[[1, 2, 3], [4, 5, 6], [7, 8, 9]]`.

**Hint:** Use the `np.array()` function to convert a Python list into a NumPy array.

In [3]:
my_list = np.array([1, 2, 3, 4, 5])

In [4]:
my_matrix = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

### 3. Create a 3x4 array of all zeros (`zeros_array`), a 2x5 array of all ones (`ones_array`), and a 4x4 identity matrix (`identity_matrix`).

In [5]:
zero_array = np.zeros([3,4])
zero_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
ones_array = np.zeros([2,5])
ones_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
identity_matrix = np.identity(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 4. Create an array of 20 evenly spaced numbers between 0 and 10 (`linear_space`) and an array of numbers from 0 to 19 with a step of 2 (`ranged_array`).

In [8]:
linear_space = np.linspace(0, 10, num = 20)
linear_space

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [9]:
ranged_array = np.arange(0,19,2)
ranged_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### 5. Create a 3x3 array of random numbers from a uniform distribution between 0 and 1 (`random_uniform`), a 3x3 array of random numbers from a standard normal distribution (`random_normal`), and a 1D array of 10 random integers between 10 and 50 (`random_integers`).

**Hint:** Use `np.random.rand()` for uniform distribution, `np.random.randn()` for standard normal distribution, and `np.random.randint()` for random integers.

In [10]:
random_uniform = np.random.rand(3,3)
random_uniform

array([[0.80387593, 0.44750732, 0.74713235],
       [0.50066225, 0.78423533, 0.3579764 ],
       [0.07883205, 0.13462934, 0.96501962]])

In [11]:
random_normal = np.random.randn(3,3)
random_normal

array([[ 0.07982047,  1.45463294, -0.57437685],
       [-1.59694681,  0.82566213,  0.40751895],
       [-0.52080704,  0.13831302, -0.77795203]])

In [12]:
random_integers = np.random.randint(10,50,size=10)
random_integers

array([39, 16, 42, 49, 47, 37, 40, 45, 26, 26], dtype=int32)

### 6. Using the `my_matrix` from Q2, print its shape, number of dimensions (ndim), data type (dtype), and total number of elements (size).

**Hint:** Use the attributes `.shape`, `.ndim`, `.dtype`, and `.size` on the NumPy array.

In [13]:
print(my_matrix.shape)

print(my_matrix.ndim)

print(my_matrix.dtype)

print(my_matrix.size)

(3, 3)
2
int64
9


### 7. Create a 1D array with 12 elements and use the `reshape()` method to change it into a 3x4 array named `reshaped_array`.

In [14]:
temp_arr = np.arange(1,13)
print(temp_arr)
reshaped_array = temp_arr.reshape(3,4)
print(reshaped_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 8. Change the data type of `reshaped_array` to `float64` and name it `float_array`.

**Hint:** Use the `.astype()` method on the array to change its data type.

In [15]:
print(reshaped_array.dtype,reshaped_array)
reshaped_array = reshaped_array.astype("float64")
print(reshaped_array.dtype, reshaped_array)

int64 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
float64 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


### 9. Get the element at the 2nd row, 3rd column (value 70) and the element at the 1st row, 1st column (value 10).

**Hint:** Use index-based access `array[row, column]`. Remember that indexing is 0-based.

### For the following questions, use this 2D array: `data = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])`

In [16]:
import numpy as np
data = np.array([[10, 20, 30, 40], 
                 [50, 60, 70, 80], 
                 [90, 100, 110, 120]])

In [17]:
data[1,2]

np.int64(70)

In [18]:
data[0,0]

np.int64(10)

### 10. Get the entire 2nd row and the entire 3rd column.

In [19]:
data[1,:]

array([50, 60, 70, 80])

In [20]:
data[:,2]

array([ 30,  70, 110])

### 11. Get a sub-array containing the first 2 rows and the first 2 columns.

In [21]:
data[0:2,0:2]

array([[10, 20],
       [50, 60]])

### 12. Get a sub-array containing the last 2 rows and the last 2 columns.

**Hint:** Use negative indexing in your slice.

In [22]:
data[-2:,-2:]

array([[ 70,  80],
       [110, 120]])

### 13. Get every second element from the 3rd row.

**Hint:** Use slicing with a step: `array[row, ::step]`.

In [23]:
data[2,1::2]

array([100, 120])

### 14. Using fancy indexing, get the elements at positions (0, 1), (1, 2), and (2, 3).

In [24]:
rows = np.array([0,1,2])
colms = np.array([1,2,3])

print(data[rows,colms])

[ 20  70 120]


### For the following questions, use this array: `bool_data = np.arange(1, 26).reshape(5, 5)`

In [25]:
bool_data = np.arange(1, 26).reshape(5, 5)
bool_data

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### 15. Select all elements in `bool_data` that are greater than 15, all that are even, and all that are divisible by 3.

**Hint:** Use boolean indexing. Create a boolean mask with a condition (e.g., `array > 15`) and use it to index the array.

In [26]:
mask1 = bool_data > 15
mask2 = bool_data % 2 == 0
mask3 = bool_data % 3 == 0

combined_mask = mask1 & mask2 & mask3
print(bool_data[combined_mask])

[18 24]


### 16. Create a new array, `bool_data_copy`, as a copy of `bool_data`. In the copy, replace all elements greater than 20 with the value -1.

In [27]:
bool_data_copy = bool_data.copy()
mask = bool_data_copy > 20
bool_data_copy[mask] = -1

bool_data_copy

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [-1, -1, -1, -1, -1]])

### 17. Select all rows in `bool_data` where the first element is even.

In [28]:
mask = bool_data[:,0] % 2 == 0
bool_data[mask]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

### 18. Select all columns in `bool_data` where the last element is divisible by 5.

In [29]:
mask = bool_data[:, -1] % 5 == 0
bool_data[mask]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### For the following questions, create two 2x3 arrays: `arr_a = np.array([[1, 2, 3], [4, 5, 6]])` and `arr_b = np.array([[10, 11, 12], [13, 14, 15]])`

In [30]:
arr_a = np.array([[1, 2, 3], [4, 5, 6]])
arr_b = np.array([[10, 11, 12], [13, 14, 15]])

### 19. Perform element-wise addition, subtraction, multiplication, and division on `arr_a` and `arr_b`.

In [31]:
arr_a + arr_b

array([[11, 13, 15],
       [17, 19, 21]])

In [32]:
arr_a - arr_b

array([[-9, -9, -9],
       [-9, -9, -9]])

In [33]:
arr_a * arr_b

array([[10, 22, 36],
       [52, 70, 90]])

In [34]:
arr_a / arr_b

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

### 20. Add a scalar value of 100 to all elements in `arr_a`.

In [35]:
arr_a + 100

array([[101, 102, 103],
       [104, 105, 106]])

### 21. Calculate the square root of every element in `arr_b`, the exponential of `arr_a`, the natural log of `arr_b`, and the sine of `arr_a`.

**Hint:** Use NumPy's universal functions: `np.sqrt()`, `np.exp()`, `np.log()`, and `np.sin()`.

In [36]:
np.sqrt(arr_a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [37]:
np.exp(arr_a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [38]:
np.log(arr_a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [39]:
np.sin(arr_a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

### 22. Compare `arr_a` and `arr_b` to find elements where `arr_b` is greater than `arr_a`. Return a boolean array.

In [40]:
bool_array = arr_b > arr_a
bool_array

array([[ True,  True,  True],
       [ True,  True,  True]])

### 23. Create a 3x3 array `matrix_c` with values 0 to 8. Create a 1D array `vector_c` with values `[10, 20, 30]`. Add `vector_c` to each row of `matrix_c`.

**Hint:** This is an example of broadcasting. NumPy will automatically add the 1D array to each row of the 2D array.

In [41]:
matrix_c = np.arange(0,9).reshape(3,3)
vector_c = np.array([10, 20, 30])

matrix_c + vector_c

array([[10, 21, 32],
       [13, 24, 35],
       [16, 27, 38]])

### 24. Create a 1D array `vector_d` with values `[1, 2, 3]`, reshape it into a 2D column vector, and add it to each column of `matrix_c`.

In [42]:
vector_d = np.array([1, 2, 3])
vector_d.reshape(3,1) + matrix_c

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

### 25. Create a 5x1 array `v1` and a 1x4 array `v2`. Add them together and determine the shape of the resulting array.

**Hint:** When adding arrays with different dimensions, broadcasting rules apply. The resulting shape will be the maximum size along each dimension.

In [43]:
v1 = np.array([1, 2, 3, 4, 5]).reshape(5,1)
v2 = np.array([6, 7, 8, 9]).reshape(1,4)

v1 + v2

array([[ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])